[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/typescript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/typescript"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200